#!/Users/lynn/venv/bin/python

import polars as pl
import sys

file_path = sys.argv[1]

df = pl.read_csv(file_path)

print()
print("CSV Length:", format(len(df),'_'))
print()
print(f'Columns: {df.columns}')
print()
