#!/bin/zsh

COMPANY="Twinkl"
tags=(
	"development"
	"meetings"
	"operations"
	"research"
)

for i in {1..$#tags}; do
    echo "$i. $tags[$i]"
done

echo -n "Choose your current project (1-$#tags): "
read TAG_NUMBER

if [[ ! $TAG_NUMBER =~ ^[0-9]+$ ]] || [ $TAG_NUMBER -lt 1 ] || [ $TAG_NUMBER -gt ${#tags[@]} ]; then
    echo "Error: Please enter a number between 1 and ${#tags[@]}"
    exit 1
fi

SELECTED_TAG=$tags[$TAG_NUMBER] 

watson start "$COMPANY" "+$SELECTED_TAG"
