#!/bin/zsh

/Users/lynn/.mac-config/ascii-table

read "recipient_name?Enter Recipient Name: "
read "recipient_email?Enter Recipient Email: "

today=$(date +"%Y-%m-%d")
filename="${today}-invoice.txt"

#------- Template Design -------
cat <<EOF > $filename
             ████████ ██    ██ ██████  ███    ███ ███████ ██████  ██  ██████ 
                ██    ██    ██ ██   ██ ████  ████ ██      ██   ██ ██ ██      
                ██    ██    ██ ██████  ██ ████ ██ █████   ██████  ██ ██      
                ██    ██    ██ ██   ██ ██  ██  ██ ██      ██   ██ ██ ██      
                ██     ██████  ██   ██ ██      ██ ███████ ██   ██ ██  ██████ 
                                                                
                                                             
----------------------------------------------------------------------------------------
                                   INVOICE: ${today}-${invoice_number}
----------------------------------------------------------------------------------------

From: Lynn Pérez                                                 Date: $(date +"%b %d, %Y")
Email: perez.businessinfo@gmail.com

To: $recipient_name
Email: $recipient_email


#{PASTE ASCII HERE}




  
                                     _________
                                    /________/|
                                    |  ____  ||  (
                                    | |    |*||   )
                                    | |____|–||__|[|_,__
                                   /[________]|  |[|( )/|
                                  /___________________/ |
                                  |  _________  _____ | |
                                  | /         ||_____|| |
                                  | |         ||_____|| |
                                  | |         ||_____|| |
                                  |_|         |_______|/



                        ╔════════════════════════════════════════╗
                        ║ A pleasure doing business with you!    ║
                        ║                Thank you.              ║
                        ╚════════════════════════════════════════╝
EOF

echo "Invoice generated as $filename"

