#!/bin/zsh

WORK_MIN=25

BREAK_MIN=5

CYCLES=4

for ((i=1;i<=CYCLES;i++))
do
	echo "Work session 1 starting in"
	sleep 1
	echo "3..."
	sleep 1
	echo "2..."
	sleep 1
	echo "1..."
	osascript -e 'display notification "Work Session Initiated" with title "B.A.S.H."' 
	afplay /System/Library/Sounds/Glass.aiff

	sleep "${WORK_MIN}m"
	echo "Work session $i completed. Time to rest."

	osascript -e 'display notification "Time for a break!" with title "B.A.S.H."'
	afplay /System/Library/Sounds/Glass.aiff

	echo "Resting for ${BREAK_MIN} minutes."
	sleep "${BREAK_MIN}m"
	
	echo "Back to work now..."
	osascript -e 'display notifiaction "Back to work now..." with title "B.A.S.H."'
	afplay /System/Library/Sounds/Glass.aiff

done

echo "Work session completed."
sleep 1
echo "Well done"
