#!/bin/zsh

if [[ $# -ne 1 ]]; then
  echo "Usage: $(basename $0) URL"
  exit 1
fi

url=$1

# Extract scheme (http or https); default to https if none
if [[ $url == *"://"* ]]; then # <-- this determineds whether a url contains ://, assuming if so, that it contains either https:// or http://
  scheme=${url%%"://"*}
  rest=${url#*"://"}
else
  scheme="https"
  rest=$url
fi

curl "${scheme}://r.jina.ai/${rest}"
