#!/bin/zsh

clipboard_content=$(pbpaste)

# Regex pattern for detecting URLs
url_pattern="^(https?|ftp)://[^\s/$.?#].[^\s]*$"

if [[ $clipboard_content =~ $url_pattern ]]; then
    # If clipboard content is a URL, pass it as an argument to fabric
    fabric -u "$clipboard_content" -p summarize | glow 
else
    # Otherwise, treat it as a normal string
    pbpaste | fabric -p summarize | glow 
fi
