#!/bin/zsh

date=$(date +"%b %d, %Y")
PINK='\033[38;5;162m'
BLUE='\033[38;5;75m'
NC='\033[0m'

clear

cd "/Users/lynn/Library/Mobile Documents/com~apple~CloudDocs/Work Files/Turmeric/Twinkl"

echo -e "${BLUE}"
echo -e "                               ████████ ██     ██ ██ ███    ██ ██   ██ ██"
echo -e "                                  ██    ██     ██ ██ ████   ██ ██  ██  ██"     
echo -e "                                  ██    ██  █  ██ ██ ██ ██  ██ █████   ██"      
echo -e "                                  ██    ██ ███ ██ ██ ██  ██ ██ ██  ██  ██"     
echo -e "                                  ██     ███ ███  ██ ██   ████ ██   ██ ███████" 
echo -e ""                                                
echo -e "-----------------------------------------------------------------------------------------------------"
echo -e "                                        HOME DIRECTORY – ${date}                            "
echo -e "-----------------------------------------------------------------------------------------------------"
echo -e "${NC}"

ls 

echo ""
