#!/bin/zsh

input_file="$1"

libreoffice_path="$(which soffice)"

echo "Opening $input_file, applying formatting, and saving as PDF..."
soffice --norestore "$input_file" "macro:///Standard.Module1.ApplyFormattingAndSaveAsPDF" &

sleep 3

pkill soffice
pkill soffice.bin

echo "Done! Thanks for sotpping by."

